### ISSUE TITLE
what is input and output of network exactly

### ISSUE THREAD

**Issue by ranch-hands** [boschresearch/OASIS#11]
hello dear all 
@SebastianSchildt @LGro @johannes-mueller @schorg @c2bo 

Does anybody knows what the input and output of this network is exactly?
does it take those labels and the output is the normal pictures?
Am I right?

thanks in advance

**Comment by edgarschnfld** [comment]
Hi, the generator inputs are a label map and a 64-dimensional gaussian noise vector (for the variation in the image). The output is a normal picture.

**Comment by LGro** [comment]
Hi @ranch-hands, even without mentioning individuals you should get a response on issues. But if you do mention folks, I'd kindly ask you to mention only maintainers or core contributors to the relevant repository in the future. Thanks and good luck with the issue.

**Comment by ranch-hands** [comment]
> Hi @ranch-hands, even without mentioning individuals you should get a response on issues. But if you do mention folks, I'd kindly ask you to mention only maintainers or core contributors to the relevant repository in the future. Thanks and good luck with the issue.

sorry dear, I'm new to this ,and your name was recommanded when I pressed @. I thought you also created this repo.

**Comment by LGro** [comment]
No worries, happy it worked out!
