### ISSUE TITLE
ADE20K-outdoor

### ISSUE THREAD

**Issue by EndlessSora** [boschresearch/OASIS#23]
Hi @SushkoVadim  @edgarschnfld ,

Thanks for the excellent work. Starting from SPADE, I noted that a series of papers provided the benchmark results on the ADE20K-outdoor dataset, a subset of ADE20K that only contains outdoor scenes, used in Qi et al. In their [repo](https://github.com/xjqicuhk/SIMS), I only found the 1,035 ADE20K-outdoor test labels their provided 'result.zip' file.

Could you please share how I can find the list/data of ADE20K-outdoor and how to train the model (train: full, test: subset; Or: train: subset, test: subset) to make a fair comparison? I ask this question only because I wish to test my model on ADE20K-outdoor.

Thank you very much for any help you may provide.

**Comment by SushkoVadim** [comment]
Hi,

I am not sure there exists an official list of the train/val splits for the ADE20K-outdoor dataset. 

To construct this dataset, we selected images in the respective splits of full ADE20K, by filtering images containing indicative classes like "sky", "mountain", "earth", and filtering out obvious indoor classes like "ceiling", "bed", "sink". After this step, we manually skimmed through the selected images and manually filtered out few remaining indoor scenes. This resulted in the train/val splits closely matching the number of images reported in other papers. (very close to 10k and 1k, as far as I remember).
You can find the full list of ADE20K classes and their IDs [here](https://github.com/CSAILVision/sceneparsing/blob/master/objectInfo150.csv).

Good luck!
