### ISSUE TITLE
Train the model with custom dataset

### ISSUE THREAD

**Issue by Ghaleb-alnakhlani** [boschresearch/OASIS#27]
Hi,

I really don`t know what exactly I need to change in the model in order to run the training.
It will be very helpful if you can tell me how to prepare the dataset for the model.
I wonder how the semantic label should look like?
Let's say we have 3 classes (pedestrian, cow, sheep) and what the target and label folder looks like.
This is how I prepared the dataset (example)
Input (**note** mask can be in any color other than red, white for example)
<img src="https://user-images.githubusercontent.com/8400931/170844637-9918d1a2-3051-45e1-9389-af9bb7618659.jpg" width=160 height=140>
![0002](https://user-images.githubusercontent.com/8400931/170844644-2cb48bca-b326-435b-b7b4-2b495a713f4e.png)
Target
<img src="https://user-images.githubusercontent.com/8400931/170844685-d74d6d7b-cc04-4f18-93dc-caffc7bd77ba.png" width=160 height=140>
<img src="https://user-images.githubusercontent.com/8400931/170844693-149eac17-0332-4b8d-a39a-d678f2446c0c.png" width=80 height=160>
Your help is highly appreciated.

**Comment by SushkoVadim** [comment]
Hi,

I think the easiest way to understand the folder structure and the label types is to have a look at one of the commonly used datasets. Taking Ade20k as an example, I would recommend you to download its contents from [this link](http://data.csail.mit.edu/places/ADEchallenge/ADEChallengeData2016.zip). 
You can see that images are stored as normal .jpg RGB images.
For the label maps, they are usually stored as grayscale maps of integer values, where each integer at each pixel location corresponds to the class ID.
For such a dataset structure, our dataloader can be found here: https://github.com/boschresearch/OASIS/blob/master/dataloaders/Ade20kDataset.py

The remaining part for you would be to convert your dataset to a similar structure.
As I could imagine, this would imply the following:
- Copy all the files into `image/`, `label/` folders. 
- Rename all the files in a way that all image-label pairs are named identically
- Convert all the label maps to the grayscale integer maps, where each value corresponds to label ID (analogously to Ade20k)
- Implement a new dataloader for your dataset, taking Ade20kDataset.py as an example. Also take a look at [this discussion](https://github.com/boschresearch/OASIS/issues/13).

Hope it helps!

**Comment by Ghaleb-alnakhlani** [comment]
I am familiar with Pix2PixHD dataset structure.
I structured the folder to one dataroot, and I there are two folders inside `train_A` `train_B`.
`!python train.py --label_nc 0 --no_instance --name obj --resize_or_crop none --dataroot /path/to/datasets`
And in OASIS it is slightly different `--label_nc` doesnt function the way it does in Pix2PixHD

**Comment by SushkoVadim** [comment]
Hi,

Both are possible. I think it depends on whether you plan to train one model for the whole dataset with all classes, or whether you want to have a separate model for each of your classes. Since there are no images having both "sheep" and "cow" classes, it makes sense to have separate models for different classes (but this is just an assumption, it totally depends on your experiment design).
Then, the structure is the first one, or the following:
```
/ dataset_sheep
   /sheep_512
   /sheep_mask
/ dataset_cow
   /cow_512
   /cow_mask
```

For the masks, I would suggest a simple test:
```
# --- read label map ---#
label = Image.open("your_label_map.png")
label = TR.functional.to_tensor(label)
print(label)
```
In your test, you should see the elements 0 and 1 (e.g., not 255). Then, 0 would correspond to background, and 1 for the cow.

----------

Yes, our structure is a bit different from Pix2PixHD, because their repository is for image-to-image translation, while ours is for semantic image synthesis. The closer repository for us is the one of SPADE (https://github.com/NVlabs/SPADE).

**Comment by Ghaleb-alnakhlani** [comment]
My bad I forgot to mention I want to train one model for the whole dataset. How the structure should look like?
Thank you for the tip on testing the mask, that is very helpful.

**Comment by SushkoVadim** [comment]
In your case, if you want to have a single model for all classes, you should organize the first option:
```
/dataset
  /target
    all the images from the 3 classes extracted here
  /label
    all the labels from the 3 classes extracted here
```
Don't forget to in all the masks background should be class 0, cow 1, sheep 2, so it has to be consistent across all the masks.

Image-to-image translation translates images to images, e.g. zebras to horses. Semantic image synthesis is a special class of Image-to-image translation that uses masks as input, not images. Your dataset type is ok for both tasks.

**Comment by Ghaleb-alnakhlani** [comment]
Hi @SnowdenLee thank you. Can you please provide an example of how to prepare my data according to what you have mentioned if you know where this is implemented before?
Another thing I noticed is there a way to keep the images unchanged, the input of the real image is (transparent) however the dataloader changes the images to RGB resulting in a black background added to the transparent image? What do I need to change in order to avoid that?
