### ISSUE TITLE
Any idea on why OASIS discriminator can encourage repetitive patterns?

### ISSUE THREAD

**Issue by s1ddok** [boschresearch/OASIS#29]
While doing my experiments I've replaced `SPADE`'s discriminator with `OASIS` one and tried this with `VGG` being both disabled and enabled. In any case images seems to be visually better (even though `FID` is higher on CityScapes) but what is very noticeable (unfortunately I can't share images) is that `OASIS` discriminator for some reason encourages repetitive patterns in result images, specifically in broad semantic regions like road. Do you have any idea what could cause that given that the only change in my model I did is replacing `MultiscaleDiscriminator` with `OASISDiscriminator`? 

I'm sorry for a vague question but I just wonder if there any obvious things I can try to fight this. I also use `LabelMix` loss with `Lambda = 10`.

**Comment by edgarschnfld** [comment]
Hi, 

Just a suspicion, but could you change the following line:
https://github.com/boschresearch/OASIS/blob/8fc1cf06e67fdbb641760080099ea720128110fd/models/generator.py#L36
To
```
z = torch.randn(seg.size(0), self.opt.z_dim, dtype=torch.float32)
z = z.to(device) 
```
And report back? A colleague of mine reported something similar to what you are describing and solved it by producing the noise on the CPU first, before removing it to GPU. He's still investigating why this makes such a big difference in his training.

In addition, you could drop labelmix for now, to reduce possible sources of error.

**Comment by s1ddok** [comment]
@edgarschnfld 

thanks for the quick answer! the problem is that I don't use 3d noise (I'm using regular spade) and I don't see any repetitive patterns with multiscale patch gan discriminator. I'll try to reduce labelmix lambda, maybe it has something to do with it

**Comment by s1ddok** [comment]
btw is there any particular reasoning you use `lambda = 5.0` for cityscapes?

**Comment by edgarschnfld** [comment]
> btw is there any particular reasoning [you use](https://github.com/boschresearch/OASIS/blob/8fc1cf06e67fdbb641760080099ea720128110fd/config.py#L83) `lambda = 5.0` for cityscapes?

Looking at the lab journal, an intermediate ablation on Cityscapes gave a ca 1 FID improvement when lambda was reduced from 10 to 5. For ADE20k, lambda 10 gave a slightly better FID than 5. Are you using a higher resolution on Cityscapes than in the paper?

**Comment by s1ddok** [comment]
no, the same but with lambda 10 I overlooked it initially. I'll try it with 5, thanks!
