### ISSUE TITLE
reported number in paper is from best or latest model?

### ISSUE THREAD

**Issue by Yuheng-Li** [boschresearch/OASIS#4]
I noticed that in the code you will calculate FID according to test images and save the best model accordingly(correct me if wrong). I am wondering if is the best model used to report numbers in the paper?   Thanks

**Comment by edgarschnfld** [comment]
Yes, this is the case. The best model is saved for reporting numbers, whereas the latest model is saved to easily resume training in case it was interrupted.

**Comment by Yuheng-Li** [comment]
Thanks
