### ISSUE TITLE
oasis.yml

### ISSUE THREAD

**Issue by kkaytekin** [boschresearch/OASIS#40]
Hi there,
[It looks like pytorch 1.0.0 is no longer in the pytorch channel](https://anaconda.org/pytorch/pytorch). I just wanted to report this, so that you might want to update your `oasis.yml`. 

Also, looking at this `.yml` file, I see packages that are not likely used by your project. If you happen to generate a new version, could you maybe give a shot to the `--from-history` flag? [It should make the `.yml` file leaner.](https://docs.readthedocs.io/en/stable/guides/conda.html#:~:text=case%20Ubuntu%20Linux.-,conda%20env%20export%20%2D%2Dfrom%2Dhistory,-will%20only%20include)

**Comment by kkaytekin** [comment]
The missing package can be found in ['anaconda' channel](https://anaconda.org/anaconda/pytorch/files?version=1.0.1). Simply adding `anaconda` to the channels list solves the issue.

**Comment by JiangYan0409** [comment]
请问，你现在复现出来了吗？
