### ISSUE TITLE
Reproduce the mIoU for cityscapes

### ISSUE THREAD

**Issue by Houssem-25** [boschresearch/OASIS#5]
Hello, 
Thank you for making the code available. 
I'm trying to reproduce the mIoU for cityscapes. I want to make sure how should I test the generated images using drn --ms.
What is the resolution when you calculate the mIoU using DRN ? do you upsample the genereted results before testing mIoU or downsample the labels?

Thanks again

**Comment by SushkoVadim** [comment]
Hi,

We use the resolution equal to the size of generated images, which is 512x256 for cityscapes.
The images should be taken from the `./results/oasis_cityscapes/best/image/,`, while the label maps should come as downsampled versions of the label maps (with nearest downsampling) from the dataset. 

Alternatively, the label maps can be taken from `./results/oasis_cityscapes/best/label/`, as they are already at correct resolution (in this case color images should be converted to 1 channel label maps, based on the [colormap](https://github.com/boschresearch/OASIS/blob/3cd94cc88e385d2b85d95b9dfcdb9adb61b0df06/utils/utils.py#L252) function).
