### ISSUE TITLE
Integrate OASIS in gan-compression

### ISSUE THREAD

**Issue by seekingdeep** [boschresearch/OASIS#6]
@edgarschnfld @SushkoVadim Hi there,
OASIS seems to have great potential,

thought it still seems that it can achieve greater efficiency by integrating it into the [Gan-Compression](https://github.com/mit-han-lab/gan-compression) workflow,
 which theoretically could **reduce the parameters by 4 times**, and r**educe the MACs by 9 times** perhaps.
They already have an implementation of SPADE (GauGAN) which you can build on top of that.

Waiting for your reply

**Comment by edgarschnfld** [comment]
Hi,

This seems like a very useful thing to do. However, we don't have time at the moment to add this feature. That being said, contributions are very much welcome :)

Best,
Edgar
